#!/usr/bin/with-contenv bash

# make our folders
echo "[INFO] make our folders"
mkdir -p \
	/config/www/gallery

# install piwigo
echo "[INFO] install piwigo"
if [ ! -f "/config/www/gallery/index.php" ]; then
	unzip -q /piwigo/piwigo.zip  -d /tmp
	mv /tmp/piwigo/* /config/www/gallery
	rm -rf /tmp/piwigo
fi

# copy config
echo "[INFO] copy config"
[[ ! -f "/config/www/gallery/local/config/config.inc.php" ]] && \
	cp /config/www/gallery/include/config_default.inc.php \
	/config/www/gallery/local/config/config.inc.php

# permissions
echo "[INFO] fix permissions"
chown -R abc:abc \
	/config

